<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.5 monstermask.glb --transform
-->

<script>
  import { T } from '@threlte/core'
  import { useGltf, useDraco } from '@threlte/extras'

  let { ref = $bindable(), color, ...props } = $props()

  const gltf = useGltf('/monstermask-transformed.glb', { dracoLoader: useDraco() })
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf then gltf}
    <T.Mesh
      geometry={gltf.nodes.MonsterMask2.geometry}
      rotation={[1.57, 0.07, -1.57]}
    >
      <T.MeshStandardMaterial {color} />
    </T.Mesh>
  {/await}
</T.Group>
